name: swagger_parser_pages
description: Web interface for swagger_parser
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.12.0

dependencies:
  archive: ^4.0.9
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  swagger_parser:
  url_launcher: ^6.3.2
  web: ^1.1.1

dev_dependencies:
  carapacik_lints: ^3.12.0

flutter:
  uses-material-design: true
