name: Deploy Flutter Web to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: github-pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        working-directory: ./swagger_parser_pages

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.23.0
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test

      - name: Build Web
        run: flutter build web --wasm --release --base-href "/${{ github.event.repository.name }}/"

      - name: Add SPA fallback
        run: cp build/web/index.html build/web/404.html

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v6.0.0

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: swagger_parser_pages/build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5.0.0
